project_id = "lylblbckiwabbnjasahu"

[functions.update-participant-score]
verify_jwt = false

[functions.generate-batch-idols]
verify_jwt = false

[functions.generate-character-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-story-image]
verify_jwt = false

[functions.analyze-conversation]
verify_jwt = false

[functions.generate-idol-image]
verify_jwt = false

[functions.generate-profile-cards]
verify_jwt = false